function J = Je_matrix(in1)
%JE_MATRIX
%    J = JE_MATRIX(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    27-Oct-2020 16:55:36

qnsh = in1(4,:);
qnsk = in1(5,:);
qsf = in1(1,:);
qsh = in1(3,:);
qsk = in1(2,:);
t2 = -qnsh;
t3 = -qnsk;
t4 = pi./2.0;
t5 = pi.*(3.0./2.0);
t6 = qsf+t4;
t10 = qsf+qsh+qsk+t2+t5;
t7 = qsk+t6;
t11 = cos(t10);
t12 = sin(t10);
t13 = t3+t10;
t8 = cos(t7);
t9 = sin(t7);
t14 = cos(t13);
t15 = sin(t13);
t19 = t12.*(2.54e+2./6.25e+2);
t20 = t11.*(2.54e+2./6.25e+2);
t16 = t8.*(2.54e+2./6.25e+2);
t17 = t9.*(2.54e+2./6.25e+2);
t21 = -t19;
t22 = t14.*4.667e-1;
t23 = t15.*4.667e-1;
t18 = -t17;
t24 = -t22;
t25 = -t23;
J = reshape([t18+t21+t25-sin(t6).*4.667e-1,t16+t20+t22+cos(t6).*4.667e-1,t18+t21+t25,t16+t20+t22,t21+t25,t20+t22,t19+t23,-t20+t24,t23,t24,1.0,0.0,0.0,1.0],[2,7]);
